# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
